name: jQA Standard CI Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build with Java ${{ matrix.java-version }} (Distribution ${{ matrix.distribution }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11 ]
        distribution: [temurin, microsoft, adopt, adopt-openj9, zulu]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-          

      - name: Compile only
        run: |
          mvn \
            -DskipTests -Djqassistant.skip \
            --batch-mode --no-transfer-progress \ 
            clean package



